"""FastAPI application for serving company recommendation articles."""

import os
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Optional

from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware

from .data_loader import get_article_index, init_article_index
from .schemas import (
    ArticleListResponse,
    ArticleResponse,
    CompanyListResponse,
    ErrorResponse,
    HealthResponse,
    PipelineMetadata,
)

# Configuration from environment variables
ARTICLES_DIR = os.getenv(
    "ARTICLES_DIR",
    "/app/output_production/article_generator/articles"
)

# For local development, use relative path if the default doesn't exist
if not Path(ARTICLES_DIR).exists():
    local_path = Path(__file__).parent.parent / "output_production" / "article_generator" / "articles"
    if local_path.exists():
        ARTICLES_DIR = str(local_path)


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Application lifespan handler - load articles on startup."""
    # Startup: Load articles
    try:
        print(f"Loading articles from: {ARTICLES_DIR}")
        index = init_article_index(ARTICLES_DIR)
        print(f"Loaded {index.total_articles} articles from {index.total_companies} companies")
    except FileNotFoundError as e:
        print(f"Warning: {e}")
        print("API will start but no articles are available.")
        # Initialize with empty index - will fail on requests
    
    yield
    
    # Shutdown: Nothing to clean up


app = FastAPI(
    title="AIHireBox Article API",
    description="REST API for serving company recommendation articles generated by the AIHireBox pipeline.",
    version="1.0.0",
    lifespan=lifespan,
)

# Enable CORS for frontend consumption
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Configure appropriately in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# =============================================================================
# Health Check
# =============================================================================

@app.get(
    "/health",
    response_model=HealthResponse,
    tags=["Health"],
    summary="Health check endpoint",
)
async def health_check():
    """Health check for load balancer and monitoring."""
    try:
        index = get_article_index()
        return HealthResponse(
            status="healthy",
            articles_loaded=index.total_articles,
            companies_count=index.total_companies,
        )
    except RuntimeError:
        return HealthResponse(
            status="degraded",
            articles_loaded=0,
            companies_count=0,
        )


# =============================================================================
# Metadata
# =============================================================================

@app.get(
    "/metadata",
    response_model=PipelineMetadata,
    responses={404: {"model": ErrorResponse}},
    tags=["Metadata"],
    summary="Get pipeline run metadata",
)
async def get_metadata():
    """Get metadata about the pipeline run that generated the articles."""
    try:
        index = get_article_index()
        if index.metadata is None:
            raise HTTPException(status_code=404, detail="No metadata available")
        return index.metadata
    except RuntimeError:
        raise HTTPException(status_code=503, detail="Article index not initialized")


# =============================================================================
# Companies
# =============================================================================

@app.get(
    "/companies",
    response_model=CompanyListResponse,
    tags=["Companies"],
    summary="List all companies with articles",
)
async def list_companies():
    """List all companies that have generated articles."""
    try:
        index = get_article_index()
        companies = index.list_companies()
        return CompanyListResponse(
            total=len(companies),
            companies=companies,
        )
    except RuntimeError:
        raise HTTPException(status_code=503, detail="Article index not initialized")


# =============================================================================
# Articles
# =============================================================================

@app.get(
    "/articles",
    response_model=ArticleListResponse,
    tags=["Articles"],
    summary="List articles with filtering and pagination",
)
async def list_articles(
    company_id: Optional[str] = Query(None, description="Filter by company ID"),
    rule_id: Optional[str] = Query(None, description="Filter by rule ID (e.g., R1_industry)"),
    style: Optional[str] = Query(None, description="Filter by style (e.g., 36kr, xiaohongshu)"),
    page: int = Query(1, ge=1, description="Page number (1-indexed)"),
    page_size: int = Query(20, ge=1, le=100, description="Items per page"),
):
    """List articles with optional filtering and pagination.

    Returns article summaries (without full content) for efficiency.
    Use the specific article endpoints to get full content.
    """
    try:
        index = get_article_index()
        summaries, total = index.list_articles(
            company_id=company_id,
            rule_id=rule_id,
            style=style,
            page=page,
            page_size=page_size,
        )
        return ArticleListResponse(
            total=total,
            page=page,
            page_size=page_size,
            articles=summaries,
        )
    except RuntimeError:
        raise HTTPException(status_code=503, detail="Article index not initialized")


@app.get(
    "/articles/{company_id}",
    response_model=list[ArticleResponse],
    responses={404: {"model": ErrorResponse}},
    tags=["Articles"],
    summary="Get all articles for a company",
)
async def get_articles_for_company(
    company_id: str,
    rule_id: Optional[str] = Query(None, description="Filter by rule ID"),
    style: Optional[str] = Query(None, description="Filter by style"),
):
    """Get all articles for a specific company.

    Optionally filter by rule_id and/or style.
    """
    try:
        index = get_article_index()
        articles = index.get_articles_for_company(
            company_id=company_id,
            rule_id=rule_id,
            style=style,
        )
        if not articles:
            raise HTTPException(
                status_code=404,
                detail=f"No articles found for company {company_id}",
            )
        return articles
    except RuntimeError:
        raise HTTPException(status_code=503, detail="Article index not initialized")


@app.get(
    "/articles/{company_id}/{rule_id}",
    response_model=list[ArticleResponse],
    responses={404: {"model": ErrorResponse}},
    tags=["Articles"],
    summary="Get articles by company and rule",
)
async def get_articles_by_rule(
    company_id: str,
    rule_id: str,
    style: Optional[str] = Query(None, description="Filter by style"),
):
    """Get articles for a company filtered by rule ID.

    Returns all styles for the given company/rule combination unless style is specified.
    """
    try:
        index = get_article_index()
        articles = index.get_articles_for_company(
            company_id=company_id,
            rule_id=rule_id,
            style=style,
        )
        if not articles:
            raise HTTPException(
                status_code=404,
                detail=f"No articles found for company {company_id} with rule {rule_id}",
            )
        return articles
    except RuntimeError:
        raise HTTPException(status_code=503, detail="Article index not initialized")


@app.get(
    "/articles/{company_id}/{rule_id}/{style}",
    response_model=ArticleResponse,
    responses={404: {"model": ErrorResponse}},
    tags=["Articles"],
    summary="Get a specific article",
)
async def get_specific_article(
    company_id: str,
    rule_id: str,
    style: str,
):
    """Get a specific article by company ID, rule ID, and style.

    This is the most specific endpoint - returns exactly one article.
    """
    try:
        index = get_article_index()
        article = index.get_article(company_id, rule_id, style)
        if article is None:
            raise HTTPException(
                status_code=404,
                detail=f"Article not found: {company_id}/{rule_id}/{style}",
            )
        return article
    except RuntimeError:
        raise HTTPException(status_code=503, detail="Article index not initialized")


# =============================================================================
# Admin Endpoints (optional)
# =============================================================================

@app.post(
    "/admin/reload",
    response_model=HealthResponse,
    tags=["Admin"],
    summary="Reload articles from disk",
)
async def reload_articles():
    """Reload all articles from disk.

    Use this after the pipeline has generated new articles.
    """
    try:
        index = get_article_index()
        index.reload()
        return HealthResponse(
            status="healthy",
            articles_loaded=index.total_articles,
            companies_count=index.total_companies,
        )
    except RuntimeError:
        raise HTTPException(status_code=503, detail="Article index not initialized")
    except FileNotFoundError as e:
        raise HTTPException(status_code=500, detail=str(e))



